### ISSUE TITLE
Users should not have user names

### ISSUE THREAD

**Issue by aivascu** [WiseKoala/OnlineLibrary#11]
The "user name" notion is redundant for this system since the user data should be imported from the user's Google account. 
The UI should show the actual first name and last name imported from the Google account.

**Comment by ioana-ianovici** [comment]
Issue has been solved and awaiting now for testing.

**Comment by hansol90** [comment]
User still can change his user name on first registration.

**Comment by ioana-ianovici** [comment]
@hansol90 How? Screenshot please.

**Comment by ioana-ianovici** [comment]
This issue is deprecated, as it is being automatically solved by the implementation of the user story described in issue #17. This issue must be closed.
