### ISSUE TITLE
Google Deny Access rights error while registering a new user.

### ISSUE THREAD

**Issue by dumitruturcan** [WiseKoala/OnlineLibrary#130]
Steps to reproduce:

1. Delete cookies from your browser(Open incognito window)
2. Access the Application
3. Click on login button
4. Enter your google account e-mail address and password
5. !!! When google asks the user to give the access rights to continue press the button "Don't allow".
6. User gets redirected to the Application login page.
7. Press the Login button again.
8. Press the button "Allow" for the Google Access.
9. **!!! User again gets redirected to the Application login page.**
10. If the user again presses the login button an some errors occur, sometimes the button isn't working(doing nothing) other times we get an HTTP Error 404.15 - Not Found.

![capture](https://cloud.githubusercontent.com/assets/18345946/15287530/2d230432-1b6c-11e6-9ff1-bd78a8b2bd62.PNG)

**Comment by hansol90** [comment]
This fault persists in Chrome browser !
