### ISSUE TITLE
System doesn't recognize "spacebar" as a character on ManageCategories page

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#153]
#Preconditions:
User should be logged as a System Administrator (Have System Admin rights)

Reproduction steps:
1. System Administrator click "ManageCategories" button from Menubar;
2. System Administrator enters a new category (for exemple "123" )
3. System Administrator click "Add" button;
6. System Administrator enters a new category 
(for exemple  spacebar + "123" )
(for exemple  "123" + spacebar )
(for exemple  n*spacebar + "123" )
(for exemple  "123" +  n*spacebar )
7. System Administrator click "Add" button;

Expected Result:
Notification : Category with such name already exists.
Actual Result:
![image](https://cloud.githubusercontent.com/assets/17526146/15576389/47d54f28-2360-11e6-9627-504416a71344.png)

**Comment by hansol90** [comment]
The same problem persists on adding new Subcategory

**Comment by alexeipancratov** [comment]
Fixed the bug

**Comment by hansol90** [comment]
For Subcategories was not fixed.

**Comment by hansol90** [comment]
![image](https://cloud.githubusercontent.com/assets/17526146/15599099/5cff8844-23e9-11e6-9d1a-b7cb48a043c1.png)

**Comment by hansol90** [comment]
![image](https://cloud.githubusercontent.com/assets/17526146/15599461/145a6fb6-23ec-11e6-86d9-0ec27a345ce7.png)

**Comment by alexeipancratov** [comment]
Please check one more time. I made some improvements related to this bug.

**Comment by hansol90** [comment]
now it's ok
