### ISSUE TITLE
Scroll bar absence

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#154]
#Preconditions:
User should be logged as a System Administrator (Have System Admin rights)

Reproduction steps:
1. System Administrator click "ManageCategories" button from Menubar;
2. System Administrator add 15 new categories;
3. System Administrator add 16'th category

Expected Result:
System Administrator can view the last category.
Actual Result:
![image](https://cloud.githubusercontent.com/assets/17526146/15578663/15035ab8-236a-11e6-9a6f-41c95cb7ed77.png)

**Comment by hansol90** [comment]
The same problem with Subcategories

**Comment by alexeipancratov** [comment]
This issue is somehow related to issue 155, right?

**Comment by hansol90** [comment]
I don't think so !

**Comment by hansol90** [comment]
This happens when user session expire.
After 30min
