### ISSUE TITLE
Added Category/Subcategory should appear first , not last

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#155]
#Preconditions:
User should be logged as a System Administrator (Have System Admin rights)

Reproduction steps:
1. System Administrator click "ManageCategories" button from Menubar;
2. System Administrator add 2 categories

Expected Result:
System Administrator can view the last category on first place in the list of categories.
Actual Result:
System Administrator can view the last category on LAST place in the list of categories.

**Comment by alexeipancratov** [comment]
Fixed the bug

**Comment by hansol90** [comment]
Great job ;)
