### ISSUE TITLE
Image file is not being deleted from project folder when a book is being edited and image is being reselected

### ISSUE THREAD

**Issue by ioana-ianovici** [WiseKoala/OnlineLibrary#163]
**Reproduction steps:**
1. System administrator edits a book information
2. System administrator selects a new file for the book cover
3. System administrator presses the "Save" button on the book edit page

**Expected Result:**
The old book cover will be removed from project folder

**Actual Result:**
The old book cover remains in the project folder.

**Comment by hnedelciuc** [comment]
Issue has been fixed.
