### ISSUE TITLE
Dublicated subcategories

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#168]
**Preconditions:**
User should be logged as a System Administrator (Have System Admin rights)

**Reproduction steps:**
1. System Administrator click "Manage" and selects "Categories" button from Menubar;
2. System Administrator click on any category that has subcategories;
3. System Administrator add a new category;

**Expected Result:**
System Administrator can view added category with 0 subcategories.

**Actual Result:**
System Administrator can view added category with subcategories from other category (that was last selected before adding a new one).

**Comment by alexeipancratov** [comment]
Fixed the bug. Please verify.
