### ISSUE TITLE
At "Add new book" procedure Book Category is "Computers & Technologies"

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#178]
**Preconditions:**
User should be logged as a System Administrator (Have System Admin rights)

**Reproduction steps:**
System Administrator click "Manage" and selects "Books" button from Menubar;
System Administrator click "Add a new book" button; 
System Administrator click "Add Category" button;

**Expected Result:**
Added field contains "Choose a category" message.

**Actual Result:**
"Computers & Technologies" category is shown as selected by default. 
(but actually it is not selected )
![image](https://cloud.githubusercontent.com/assets/17526146/15781062/21c05cc6-29ad-11e6-87d1-f7fbe2ff242c.png)

**Comment by ioana-ianovici** [comment]
Issue has been fixed.
