### ISSUE TITLE
Screen hangs up when trying to register user

### ISSUE THREAD

**Issue by hnedelciuc** [WiseKoala/OnlineLibrary#21]
After authenticating with Google account successfully, user presses "Register" button at the next screen, but application stops responding (as seen in attached screenshot).
![screenshot_bug_registeringuserscreenhangup](https://cloud.githubusercontent.com/assets/18210696/14526690/bd9f657e-024d-11e6-9115-b81fed88c005.png)
If user tries to access the home page: https://localhost:44300/ he is able to do it, and actually can see that he was indeed registered in the system, BUT is unable to see Roles page.
![screenshot_bug_homepageshowsthatuserwasregistered](https://cloud.githubusercontent.com/assets/18210696/14526772/54f67322-024e-11e6-9125-e0662f1dd0c6.png)

**Comment by ioana-ianovici** [comment]
Issue has been fixed

**Comment by ioana-ianovici** [comment]
Issue has been fixed

**Comment by ioana-ianovici** [comment]
Issue has been fixed

**Comment by ioana-ianovici** [comment]
Issue has been fixed

**Comment by ioana-ianovici** [comment]
Issue has been fixed
