### ISSUE TITLE
Super Admin user can not view/access "Roles" page

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#31]
When super admin is logged in , he could not access "Roles" page !
![image](https://cloud.githubusercontent.com/assets/17526146/14604245/3c82decc-057b-11e6-8e58-6963a9276121.png)

**Comment by alexandrudascal** [comment]
This bug is resolved. I am waiting an answer from testers

**Comment by hansol90** [comment]
thank you !
