### ISSUE TITLE
Random Roles display on display page

### ISSUE THREAD

**Issue by dumitruturcan** [WiseKoala/OnlineLibrary#36]
When the first user enters the application in order to assign him self as an System Administrator, the roles are changing their locations.
**Steps to reproduce:**
-if you already used the application earlier - delete the database and rerun the application so it will generate the database with no users in it(except the Super Admin User).
- Reproduce more times the the steps of a first user login after deleting the databse for more times.
    -Press on Log In
    - Log In With Google
    - Allow Access 
    - **!!** Remember the order of the roles in the grid  **!!**
    - Assign your self as a super admin.

Repeat this steps multiple times

Photo results:
![capture](https://cloud.githubusercontent.com/assets/18345946/14607866/1dc293a4-058c-11e6-92b8-65afd60293e1.PNG)
![capture1](https://cloud.githubusercontent.com/assets/18345946/14607937/6626e6b8-058c-11e6-8123-8c0324a533ad.PNG)

**Comment by ioana-ianovici** [comment]
the bug has been solved in issue  #35

**Comment by dumitruturcan** [comment]
thank you

**Comment by hansol90** [comment]
On first user login, this problem presists

**Comment by hansol90** [comment]
Random roles categories !
