### ISSUE TITLE
Incorrect name of "System administrator" role

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#4]
In user's stories form backlog, the role of admin is named as "System administrator", but in our table with roles we have role named as "Admin", can you fix this ? 
![capture](https://cloud.githubusercontent.com/assets/17526146/14349010/b687bdc0-fcc8-11e5-9eee-99728fc02fe5.PNG)

**Comment by hnedelciuc** [comment]
Fixed Issue #4.

Role name "Admin" has been changed to "System administrator" as requested.

**Comment by hansol90** [comment]
thank you !
