### ISSUE TITLE
A logged user can Loan the same book more times then the number of available copies

### ISSUE THREAD

**Issue by dumitruturcan** [WiseKoala/OnlineLibrary#41]
As a registered user i can loan the same book (if it's available) several times, even more than the number of books available for loan

![capture](https://cloud.githubusercontent.com/assets/18345946/14707411/6698a1de-07cd-11e6-91ef-9d7ca36ba9a4.PNG)

![capture2](https://cloud.githubusercontent.com/assets/18345946/14707389/45c3b34a-07cd-11e6-9034-3c6e4a1995db.PNG)

**Comment by ioana-ianovici** [comment]
The issue is fixed.

**Comment by dumitruturcan** [comment]
Re-tested.
