### ISSUE TITLE
On window resizing, "Hello, Super Admin" is a button

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#43]
![image](https://cloud.githubusercontent.com/assets/17526146/14709863/8f2fff12-07db-11e6-9f1f-b3468ebc8654.png)
Here you can see that "Hello, Super Admin" is a button in this menu.

**Comment by dumitruturcan** [comment]
not only "Super Admin" but any user

**Comment by ioana-ianovici** [comment]
Issue has been solved.

**Comment by ioana-ianovici** [comment]
Issue has been solved and design has been improved.
