### ISSUE TITLE
After Registration , user can see the "Register." form

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#6]
![image](https://cloud.githubusercontent.com/assets/17526146/14350148/483347e2-fcd0-11e5-9338-53374c75fae9.png)
After this step , when user enters his User Name;
User clicks on "Register " and get's on home page.

After that , he should not be able to turn back, and change the "User Name" .
this functionality will be able only in "edit account ".

After that user clicks on back button, and changed the user name;
User clicks on "Register " and get's  something like that : 

![image](https://cloud.githubusercontent.com/assets/17526146/14350514/6e245fd4-fcd2-11e5-8c1d-9d965c3b7eb4.png)

**Comment by aivascu** [comment]
Invalid issue. See issue #11
