### ISSUE TITLE
On "https://localhost:44300/power" should not be the "Log in" button

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#60]
When Super Administator access login page "https://localhost:44300/power" he has "Log in" button.
On this page, Super Administrator want to be logged in as a Super Administrator, he should not see the "Log in " button. 
![image](https://cloud.githubusercontent.com/assets/17526146/14850329/f137af12-0c80-11e6-9268-41fd649a1cc0.png)

**Comment by hnedelciuc** [comment]
Why should he not be able to see the Log In button? What if he changes his mind after accessing /power page and suddenly wants to Log In as a different user? Why is this a bug?

**Comment by aivascu** [comment]
I agree with @hnedelciuc . I don't see a problem in having the "Log In" button on the super administrator login page ...if we intend to use the default layout for this page.
Have a look at [this plunk](http://embed.plnkr.co/iZH38LSNCWLTG4G9jl9O/) an let me know what you think.

**Comment by hansol90** [comment]
Client is always right !
