### ISSUE TITLE
Same book copy can be approved (loaned) multiple times concurrently

### ISSUE THREAD

**Issue by alexeipancratov** [WiseKoala/OnlineLibrary#64]
**Reproduction steps:**

1. Registered user clicks the Loan button
2. Librarian wants to approve this loan, presses the "Approve" button and enters Book Copy ID of the book that is either approved or loaned already

**Expected result:**
Librarian must be notified that the book copy for which the Book Copy ID was provided is not available for loan.

**Actual result:**
The Book Copy ID that the librarian has entered is accepted even when the actual book copy is not available for loan.

**Comment by aivascu** [comment]
Please add a description /w reproduction steps
