### ISSUE TITLE
Empty password field on Super Administrator log in page

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#65]
On Super Administrator login page , Super Administrator doesn't enter the password and click  "OK" button to login. In result Super Administrator get this error message >> 
![image](https://cloud.githubusercontent.com/assets/17526146/14878108/143d5bca-0d2a-11e6-8cd0-e8b91160299b.png)

**Comment by ioana-ianovici** [comment]
issue has been solved.

**Comment by hansol90** [comment]
Thank you !
