### ISSUE TITLE
User Name field - unlimited characters

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#7]
![image](https://cloud.githubusercontent.com/assets/17526146/14351886/83c5f14c-fcda-11e5-97fe-1f690dbc59b6.png)
after user clicked "Register"  system shows :
![image](https://cloud.githubusercontent.com/assets/17526146/14351947/d35bee32-fcda-11e5-97d6-c3395468eab8.png)

after user enters a lot of characters in this field, system shows : 
![image](https://cloud.githubusercontent.com/assets/17526146/14352229/263e5d0a-fcdc-11e5-9354-290df7598b86.png)

**Comment by aivascu** [comment]
Invalid issue. Override by #11 .
