### ISSUE TITLE
Move OAuth authentication options to the web.config file

### ISSUE THREAD

**Issue by aivascu** [WiseKoala/OnlineLibrary#73]
Move OAuth authentication options from Startup.Auth.cs to the web.config file.
Use a separate configuration file import the options into the web.config file.
See [link ](http://www.asp.net/identity/overview/features-api/best-practices-for-deploying-passwords-and-other-sensitive-data-to-aspnet-and-azure) for more info.

**Comment by alexandrudascal** [comment]
This task is done
