### ISSUE TITLE
User Interface on Registration page

### ISSUE THREAD

**Issue by hansol90** [WiseKoala/OnlineLibrary#8]
![image](https://cloud.githubusercontent.com/assets/17526146/14352377/de06fd3e-fcdc-11e5-889c-f8d95c266619.png)

Can you change the following words : 
- Register.    >>> Registration or Online Library Registration or Sign Up 
- Register button >>> Create account (optional)
- Finish logging in >>> "finish registration" , because on this page user create's an account and this message is specific only for Registration page .

**Comment by aivascu** [comment]
Invalid issue. See issue #11
